CREATE OR REPLACE VIEW VIEW_LOT_INFORMATION AS
    SELECT 
        LOT_INV.MAT_LOT_NO            AS LOT_NUMBER, 
        LOT_INV.PART_NO               AS PART_NUMBER,
        ERP_MAT.MAT_NM                AS PART_NAME, 
        LOT_INV.EO_NO                 AS EO_NUMBER,                  
        NVL(LOT_INV.QTY, 0)           AS QTY, 
        LOT_INV.UNIT                  AS UNIT, 
        LOT_INV.STORAGE_CODE          AS STORAGE_CODE,     
        STORAGE.STORAGE_NAME_EN       AS STORAGE, 
        LOT_INV.LOC_NO                AS LOCATION, 
        LOT_INV.CASE_LABEL_ID         AS CASE_LABEL_ID,
        CASE WHEN VENDOR.VEN_ID IS NOT NULL THEN VENDOR.VEN_ID ELSE LOT_INV.VEN_ID END AS VENDOR_CODE,
        CASE WHEN VENDOR.VEN_ID IS NOT NULL THEN VENDOR.VEN_NM ELSE 'HYUNDAIWIA CORPORATION' END AS VENDOR, 
        LOT_INV.IN_DATE               AS INPUT_DATE,
        LOT_INV.PROD_DATE             AS PRODUCTION_DATE, 
        NVL(LOT_INV.DEFECT_FLAG, 'N') AS HAS_DEFECT, 
        NVL(LOT_INV.INSP_FLAG  , 'N') AS HAS_INSPECTION,
        NVL(EO_MAT.USE_FLAG    , 'Y') AS HAS_EO,
         NVL(LOT_INV.DEL_FLAG  , 'N') AS IS_DELETED      
    FROM MES_INV_LOT_TK         LOT_INV
    INNER JOIN MES_STORAGE_MA   STORAGE ON STORAGE.STORAGE_CODE = LOT_INV.STORAGE_CODE
    LEFT JOIN IF_ERP_MAT        ERP_MAT ON ERP_MAT.MAT_ID       = LOT_INV.PART_NO
    LEFT JOIN MES_INV_MAT_EO_MA EO_MAT  ON EO_MAT.PART_NO       = LOT_INV.PART_NO AND EO_MAT.EO_NO = LOT_INV.EO_NO
    LEFT JOIN IF_ERP_VENDOR     VENDOR  ON VENDOR.VEN_ID        = LOT_INV.VEN_ID;