CREATE OR REPLACE VIEW VIEW_USER AS
    SELECT 
        USR.USR_ID      AS "USER", 
        USR.USR_EN_NM   AS FULL_NAME,
        USR.EMAIL       AS EMAIL,
        USR.FACTORY     AS FACTORY,
        USR.DEPT_CD     AS DEPARTMENT_CODE,
        DEPT.DEPT_EN_NM AS DEPARTMENT,
        NVL(USR.USE_YN, 'N') AS USE_YN
    FROM ESAUSER USR
    LEFT JOIN ESAOGDP DEPT ON DEPT.DEPT_CD = USR.DEPT_CD;