USE [HWMXCore]
GO
 
CREATE ROLE MES_APPLICATIONS;
GO

CREATE LOGIN WIMXPD260012 WITH PASSWORD = 'W1@hyund@!U23r8y@@pp';
GO
 
CREATE USER WIMXPD260012 FOR LOGIN WIMXPD260012;
GO

ALTER ROLE MES_APPLICATIONS ADD MEMBER WIMXPD260012;
GO

GRANT CONTROL ON DATABASE::HWMXCore TO [MES_APPLICATIONS];
GO

