CREATE OR REPLACE FUNCTION FC_INCLUDE(P_STRING VARCHAR2, P_STRING2 VARCHAR2) 
    RETURN VARCHAR2
AS BEGIN
   IF INSTR(
       TRIM(NVL(P_STRING, '')), 
       TRIM(NVL(P_STRING2, ''))
   ) > 0 THEN
        RETURN 'Y'; 
   ELSE
        RETURN 'N';
   END IF;
END;