CREATE OR REPLACE FUNCTION FN_INNER_JOIN_IF(P_VALUE1 IN VARCHAR2, P_VALUE2 VARCHAR2) 
    RETURN VARCHAR2
AS BEGIN
    IF P_VALUE2 IS NULL THEN
        RETURN 'Y';
    ELSIF TRIM(P_VALUE2) IS NULL THEN
        RETURN 'Y';
    ELSE
        RETURN CASE WHEN P_VALUE1 = P_VALUE2 THEN 'Y' ELSE 'N' END;
    END IF; 
END;