CREATE OR REPLACE FUNCTION FN_IS_NOT_EMPTY(P_STRING VARCHAR2) 
    RETURN VARCHAR2
AS BEGIN
    IF P_STRING IS NULL THEN
        RETURN 'N';
    ELSIF TRIM(P_STRING) IS NULL THEN
        RETURN 'N';
    ELSE
        RETURN 'Y';
    END IF;
END;