CREATE OR REPLACE FUNCTION FN_IS_EMPTY(P_STRING VARCHAR2) 
    RETURN VARCHAR2
AS BEGIN
    IF P_STRING IS NULL THEN 
        RETURN 'Y';
    ELSIF TRIM(P_STRING) IS NULL THEN
        RETURN 'Y';
    ELSE
        RETURN 'N';
    END IF;
END;