CREATE OR REPLACE FUNCTION FN_SPLIT(P_STRING VARCHAR2, P_DELIMITER VARCHAR2 DEFAULT ';')
    RETURN ARRAY_STRING PIPELINED
AS BEGIN
    FOR i IN 1 .. REGEXP_COUNT(P_STRING, P_DELIMITER) + 1 LOOP
        PIPE ROW (REGEXP_SUBSTR(P_STRING, '[^' || P_DELIMITER || ']+', 1, i));
    END LOOP;
    RETURN;
END; 