CREATE OR REPLACE FUNCTION FN_TABLE_STRING(P_STRING IN VARCHAR2, P_DELIMITER VARCHAR2 DEFAULT ';') 
    RETURN ARRAY_STRING
IS
    V_RESPONSE ARRAY_STRING := ARRAY_STRING();
BEGIN
    IF FN_IS_NOT_EMPTY(P_STRING) = 'Y' THEN        
        SELECT COLUMN_VALUE
        BULK COLLECT INTO V_RESPONSE
        FROM TABLE(FN_SPLIT(P_STRING, P_DELIMITER));
    ELSE
        V_RESPONSE := ARRAY_STRING(NULL);
    END IF;

    RETURN V_RESPONSE;
END;