CREATE OR REPLACE PACKAGE PKG_HWMX_PDA_LOCATION AS 

    /* GET_LOT_LIST_BY_CASE_LABEL */
    PROCEDURE GET_LOT_LIST_BY_CASE_LABEL (
        P_CASE_LABEL_ID IN  VARCHAR2,
        IO_CURSOR       OUT SYS_REFCURSOR
    );


    /* GET_MATERIAL_BY_LOCATION */
    PROCEDURE GET_MATERIAL_BY_LOCATION (
        P_LOCATION IN  VARCHAR2,
        IO_CURSOR  OUT SYS_REFCURSOR
    ); 


    /* SET_LOTS_IN_LOCATION */
    PROCEDURE SET_LOTS_IN_LOCATION (
        P_LOT_NO       IN  ARR_VALUE,
        P_STORAGE_CODE IN  VARCHAR2,
        P_LOC_NO       IN  VARCHAR2,
        P_USER_ID      IN  VARCHAR2,
        IO_MESSAGE     OUT VARCHAR2
    );
    

    /* SET_LOTS_IN_LOCATION */
    PROCEDURE GET_ISSUE_REQ_LIST (
        P_ISSUE_NO IN  VARCHAR2,
        IO_CURSOR  OUT SYS_REFCURSOR
    );


    /* GET_TROLLY_ORDER */
    PROCEDURE GET_TROLLY_ORDER (
        P_PROD_DATE    IN  VARCHAR2,
        P_PLAN_SEQ     IN  VARCHAR2,
        P_TROLLY_GROUP IN  VARCHAR2,
        IO_CURSOR      OUT SYS_REFCURSOR
    );


    /* GET_LOTS_IN_TROLLY */
    PROCEDURE GET_LOT_IN_TROLLY (
        P_LOT_NO  IN  VARCHAR2, 
        IO_CURSOR OUT SYS_REFCURSOR
    );


    /* SET_ORDER_TROLLY */
    PROCEDURE SET_ORDER_TROLLY (
        P_PROD_DATE  IN  VARCHAR2,
        P_PLAN_SEQ   IN  VARCHAR2,
        P_LOT_NO     IN  ARR_VALUE,
        P_USER_ID    IN  VARCHAR2,
        IO_MESSAGE   OUT VARCHAR2   
    );


    /* SET_INVENTORY_CELL */
    PROCEDURE SET_INVENTORY_CELL (
        P_LOC_NO     IN  VARCHAR2,
        P_MAT_LOT_NO IN  ARR_VALUE,
        P_USER_ID    IN  VARCHAR2,
        IO_MESSAGE   OUT VARCHAR2
    );
END PKG_HWMX_PDA_LOCATION;