CREATE OR REPLACE PACKAGE PKG_HWMX_DELIVERY AS 

	/* GET_GATE_PERMIT */
    PROCEDURE GET_GATE_PERMIT(
        P_SHIP_NO IN  VARCHAR2, 
        IO_CURSOR OUT SYS_REFCURSOR
    );

    /* SET_GATE_PERMIT */
    PROCEDURE SET_GATE_PERMIT
    (
        P_GATE_POS          IN  VARCHAR2,
        P_SHIP_NO           IN  VARCHAR2,
        P_USER_ID           IN  VARCHAR2,
        P_RETURN_MSG        OUT VARCHAR2
    );

    PROCEDURE GET_GATE_PERMIT_DETAIL(
        P_SHIP_NO IN  VARCHAR2, 
        IO_CURSOR OUT SYS_REFCURSOR
    );

END PKG_HWMX_DELIVERY;