CREATE OR REPLACE PACKAGE PKG_HWMX_PDA_STORE AS 
    
    /* GET_LP_ENTRY */
    PROCEDURE GET_LP_ENTRY(
        P_VBELG   IN  VARCHAR2,
        IO_CURSOR OUT SYS_REFCURSOR
    );


    /* SET_LP_ENTRY */
    PROCEDURE SET_LP_ENTRY(
        P_VBELG    IN  VARCHAR2,
        P_USER_ID  IN  VARCHAR2,
        IO_MESSAGE OUT VARCHAR2
    );


    /* GET_CC_ENTRY */
    PROCEDURE GET_CC_ENTRY(
        P_DELIVERY_NO IN  VARCHAR,
        IO_CURSOR     OUT SYS_REFCURSOR
    );


    /* SET_CC_ENTRY */
    PROCEDURE SET_CC_ENTRY(
        P_DELIVERY_NO IN VARCHAR2,
        P_USER_ID     IN  VARCHAR2,
        IO_MESSAGE    OUT VARCHAR2
    );


    /* GET_GKD_ENTRY */
    PROCEDURE GET_GKD_ENTRY(
        P_LOT_NO  IN  VARCHAR2,
        IO_CURSOR OUT SYS_REFCURSOR
    ); 


    /* SET_GKD_ENTRY */
    PROCEDURE SET_GKD_ENTRY(
        P_LOT_NO    IN  VARCHAR2,
        P_PART_NO   IN  VARCHAR2,
        P_QTY       IN  VARCHAR2,
        P_UNIT      IN  VARCHAR2,
        P_PROD_DATE IN  VARCHAR2,
        P_EO_NO     IN  VARCHAR2,
        P_VD_CD     IN  VARCHAR2,
        P_WH_CD     IN  VARCHAR2,
        P_MODEL     IN  VARCHAR2,
        P_USER_ID   IN  VARCHAR2,
        IO_MESSAGE  OUT VARCHAR2
    );


    /* SET_GKD_ENTRY_AONE */
    PROCEDURE SET_GKD_ENTRY_AONE(
        P_VBELG    IN  VARCHAR2,
        P_USER_ID  IN  VARCHAR2,
        IO_MESSAGE OUT VARCHAR2
    );


    /* GET_CONTAINER_DOWNLOAD */
    PROCEDURE GET_CONTAINER_DOWNLOAD(  
        P_ORD_NO  IN  VARCHAR2,  
        IO_CURSOR OUT SYS_REFCURSOR
    );


    /* SET_CONTAINER_DOWNLOAD */
    PROCEDURE SET_CONTAINER_DOWNLOAD(
        P_ORD_NO        IN  VARCHAR2,
        P_CASE_LABEL_ID IN  ARR_VALUE,
        P_USER_ID       IN  VARCHAR2,
        IO_MESSAGE      OUT VARCHAR2
    );


    /* GET_CONTAINER_LOAD */
    PROCEDURE GET_CONTAINER_LOAD(  
        P_ORD_NO  IN  VARCHAR2, 
        IO_CURSOR OUT SYS_REFCURSOR
    );


    /* SET_CONTAINER_LOAD */
    PROCEDURE SET_CONTAINER_LOAD(
        P_ORD_NO        IN  VARCHAR2,
        P_CASE_LABEL_ID IN  ARR_VALUE,
        P_USER_ID       IN  VARCHAR2,
        IO_MESSAGE      OUT VARCHAR2
    );


    /* CHECK_CONTAINER_ORDER */
    PROCEDURE CHECK_CONTAINER_ORDER(
        P_ORD_NO        IN  VARCHAR2,
        P_CASE_LABEL_ID IN  VARCHAR2,
        IO_MESSAGE      OUT VARCHAR2
    );

END PKG_HWMX_PDA_STORE;