CREATE OR REPLACE PACKAGE PKG_HWMX_LOT AS  

    /* GET_INSPECTION_NUMBER_LIST */
    PROCEDURE GET_INSPECTION_NUMBER_LIST (
        P_STORAGE_CODE IN  VARCHAR2,
        P_RANGE        IN  NUMBER,
        IO_CURSOR      OUT SYS_REFCURSOR
    );


    /* CREATE_INSPECTION_NUMBER */
    PROCEDURE CREATE_INSPECTION_NUMBER (
        P_STORAGE_CODE IN  VARCHAR2,
        P_USER_ID      IN  VARCHAR2,
        IO_VALUE       OUT VARCHAR2
    );


    /* MOVE_LOT */
    PROCEDURE MOVE_LOT (
        P_LOT_NO       IN  VARCHAR2,
        P_STORAGE_CODE IN  VARCHAR2,
        P_USER_ID      IN  VARCHAR2,
        IO_MESSAGE     OUT VARCHAR2
    );


    /* SET_LOT_INSPECTION */
    PROCEDURE SET_LOT_INSPECTION (
        P_STORAGE_CODE IN  VARCHAR2,
        P_INSP_NO      IN  VARCHAR2,
        P_LOT_NO       IN  ARR_VALUE,
        P_USER_ID      IN  VARCHAR2,
        IO_MESSAGE     OUT VARCHAR2
    );


    /* JOIN_LOT */
    PROCEDURE JOIN_LOT (
        P_LOT_NO    IN  VARCHAR2,
        P_PRINT_CNT IN  VARCHAR2,
        P_PRINTER   IN  VARCHAR2,
        P_USER_ID   IN  VARCHAR2,
        IO_MESSAGE  OUT VARCHAR2
    );


    /* SPLIT_LOT */
    PROCEDURE SPLIT_LOT (
        P_LOT_NO     IN  VARCHAR2,
        P_SPLIT_QTY  IN  NUMBER,
        P_PRINT_CNT  IN  VARCHAR2,
        P_PRINTER    IN  VARCHAR2,
        P_USER_ID    IN  VARCHAR2,
        P_NEW_LOT_NO OUT VARCHAR2,
        IO_MESSAGE   OUT VARCHAR2
    );
END PKG_HWMX_LOT;