CREATE OR REPLACE PACKAGE PKG_HWMX_PDA_LOCATION AS 

    /* GET_MATERIAL_BY_LOCATION */
    PROCEDURE GET_MATERIAL_BY_LOCATION (
        P_LOCATION IN  VARCHAR2,
        P_CURSOR   OUT SYS_REFCURSOR
    );

    /* SET_LOTS_IN_LOCATION */
    PROCEDURE SET_LOTS_IN_LOCATION (
        P_LOT_NO       IN  ARR_VALUE,
        P_STORAGE_CODE IN  VARCHAR2,
        P_LOC_NO       IN  VARCHAR2,
        P_USER_ID      IN  VARCHAR2,
        P_RETURN_MSG   OUT VARCHAR2
    ); 
END PKG_HWMX_PDA_LOCATION;