CREATE OR REPLACE PACKAGE PKG_HWMX_MASTER AS 

    /* LOGIN */
    PROCEDURE LOGIN(
        P_USER    IN  VARCHAR2, 
        P_USER_PW IN  VARCHAR2, 
        IO_CURSOR OUT SYS_REFCURSOR
    );
    

    /* GET_USER */
    PROCEDURE GET_USER(
        P_USER    IN  VARCHAR2,
        IO_CURSOR OUT SYS_REFCURSOR
    );


    /* GET_USER_LIST */
    PROCEDURE GET_USER_LIST( 
        P_DEPT_CD     IN  VARCHAR2, 
        P_ONLY_ACTIVE IN  VARCHAR2, 
        IO_CURSOR     OUT SYS_REFCURSOR
    );
    

    /* GET_LOT_INFORMATION */
    PROCEDURE GET_LOT_INFORMATION(
        P_LOT_NUMBER IN  VARCHAR2, 
        IO_CURSOR    OUT SYS_REFCURSOR
    );

    
    /* GET_LOT_LIST_BY_CASE_LABEL */
    PROCEDURE GET_LOT_LIST_BY_CASE_LABEL(
        P_CASE_LABEL_ID IN  VARCHAR2, 
        P_STORAGE_CODE  IN  VARCHAR2, 
        IO_CURSOR       OUT SYS_REFCURSOR
    );
    

    /* GET_LOT_LIST_BY_LOCATION */
    PROCEDURE GET_LOT_LIST_BY_LOCATION(
        P_LOC_NO  IN  VARCHAR2, 
        IO_CURSOR OUT SYS_REFCURSOR
    );

    
    /* GET_STORAGE_LIST */
    PROCEDURE GET_STORAGE_LIST(
        P_FACTORY      IN  VARCHAR2, 
        P_STORAGE_TYPE IN  VARCHAR2, 
        IO_CURSOR      OUT SYS_REFCURSOR
    );
    

    /* GET_LOCATION */
    PROCEDURE GET_LOCATION(
        P_LOC_NO    IN  VARCHAR2, 
        P_RACK      IN VARCHAR2,
        P_RACK_TYPE IN  VARCHAR2, 
        IO_CURSOR   OUT SYS_REFCURSOR
    );
    

    /* GET_PRINTER_LIST */
    PROCEDURE GET_PRINTER_LIST(
        P_PRINTER_NAME IN  VARCHAR2, 
        P_CURSOR       OUT SYS_REFCURSOR
    );
END PKG_HWMX_MASTER;