/* CREATE ROLE */
CREATE ROLE MES_APPLICATIONS;  
    
/* CREATE USER */
CREATE USER WIMXPD260012 IDENTIFIED BY "W1@hyund@!U23r8y@@pp"
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
ACCOUNT UNLOCK;
     
/* SET QUOTA */
ALTER USER WIMXPD260012 QUOTA UNLIMITED ON USERS;  
    
/* SET ROLE */
GRANT CONNECT  TO WIMXPD260012;
GRANT RESOURCE TO WIMXPD260012;
GRANT MES_APPLICATIONS TO WIMXPD260012;
GRANT CREATE SESSION TO WIMXPD260012;
ALTER USER WIMXPD260012 DEFAULT ROLE MES_APPLICATIONS; 
         
/* GRANT OBJECTS */
BEGIN
    --TABLE
    FOR MES IN(SELECT TABLE_NAME FROM ALL_TABLES WHERE OWNER = 'MESADMIN') LOOP
        EXECUTE IMMEDIATE 'GRANT SELECT, INSERT, UPDATE, DELETE ON MESADMIN.' || MES.TABLE_NAME || ' TO MES_APPLICATIONS';
        EXECUTE IMMEDIATE 'CREATE OR REPLACE SYNONYM WIMXPD260012.' || MES.TABLE_NAME || ' FOR MESADMIN.' || MES.TABLE_NAME;
    END LOOP;
    
    --PROCEDURE & PACKAGE
    FOR MES IN(SELECT OBJECT_NAME FROM ALL_OBJECTS WHERE OWNER = 'MESADMIN' AND OBJECT_TYPE IN('PROCEDURE', 'PACKAGE')) LOOP
        EXECUTE IMMEDIATE 'GRANT EXECUTE ON MESADMIN.' || MES.OBJECT_NAME || ' TO MES_APPLICATIONS';
        EXECUTE IMMEDIATE 'CREATE OR REPLACE SYNONYM WIMXPD260012.' || MES.OBJECT_NAME || ' FOR MESADMIN.' || MES.OBJECT_NAME;
    END LOOP;
    
    --VIEW
    FOR MES IN(SELECT OBJECT_NAME FROM ALL_OBJECTS WHERE OWNER = 'MESADMIN' AND OBJECT_TYPE IN('VIEW')) LOOP
        EXECUTE IMMEDIATE 'GRANT SELECT ON MESADMIN.' || MES.OBJECT_NAME || ' TO MES_APPLICATIONS';
        EXECUTE IMMEDIATE 'CREATE OR REPLACE SYNONYM WIMXPD260012.' ||  MES.OBJECT_NAME || ' FOR MESADMIN.' || MES.OBJECT_NAME;
    END LOOP; 
    
    --TYPE
    FOR MES IN (SELECT OBJECT_NAME FROM ALL_OBJECTS WHERE OWNER = 'MESADMIN' AND OBJECT_TYPE = 'TYPE') LOOP
        EXECUTE IMMEDIATE 'GRANT EXECUTE ON MESADMIN.' || MES.OBJECT_NAME || ' TO MES_APPLICATIONS';
        EXECUTE IMMEDIATE 'CREATE OR REPLACE SYNONYM WIMXPD260012.' || MES.OBJECT_NAME || ' FOR MESADMIN.' || MES.OBJECT_NAME;
    END LOOP;
END;