USE [HWMXCore]
GO
  
BEGIN 
	CREATE ROLE MES_APPLICATIONS;
		
	CREATE LOGIN WIMXPD260012 WITH PASSWORD = 'W1@hyund@!U23r8y@@pp';
		 
	CREATE USER WIMXPD260012 FOR LOGIN WIMXPD260012;
		
	ALTER ROLE MES_APPLICATIONS ADD MEMBER WIMXPD260012;
		
	GRANT CONTROL ON DATABASE::HWMXCore TO [MES_APPLICATIONS];
END
GO 