<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="HWMXCore\Database\" />
  </ItemGroup>

  <ItemGroup>
    <None Include="HWMENMES\Interfaces\IESAAURF_Repository.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="HWMX.DotNet.ORM" Version="1.0.12" />
  </ItemGroup>

</Project>
