CREATE OR REPLACE PACKAGE BODY PKG_HWMX_MASTER AS  
    
    /* LOGIN */
    PROCEDURE LOGIN(
        P_USER    IN  VARCHAR2,
        P_USER_PW IN  VARCHAR2,
        IO_CURSOR OUT SYS_REFCURSOR
    )IS BEGIN

        OPEN IO_CURSOR FOR
        SELECT USRV.*
        FROM ESAUSER USR
        INNER JOIN VIEW_USER USRV ON USRV."USER" = USR.USR_ID
        WHERE USR.USR_ID     = P_USER
          AND USRV.IS_ACTIVE = 'Y'
          AND USR.SYS_ID     = '100'
          AND CryptIT.DECRYPT(USR.PW) = P_USER_PW;      
    END LOGIN;


    /* GET_USER */
    PROCEDURE GET_USER(
        P_USER    IN VARCHAR2, 
        IO_CURSOR OUT SYS_REFCURSOR
    )IS BEGIN

        OPEN IO_CURSOR FOR
        SELECT USR.*
        FROM VIEW_USER USR
        WHERE P_USER = USR."USER";      
    END GET_USER;


    /* GET_USER_LIST */
    PROCEDURE GET_USER_LIST( 
        P_DEPT_CD     IN VARCHAR2,
        P_ONLY_ACTIVE IN VARCHAR2,
        IO_CURSOR     OUT SYS_REFCURSOR
    )IS BEGIN

        OPEN IO_CURSOR FOR
        SELECT *
        FROM VIEW_USER USR
        WHERE (P_DEPT_CD IS NULL   OR P_DEPT_CD = USR.DEPARTMENT_CODE)
          AND (P_ONLY_ACTIVE = 'N' OR USR.IS_ACTIVE = 'Y');      
    END GET_USER_LIST;


    /* GET_LOT_INFORMATION */
    PROCEDURE GET_LOT_INFORMATION(
        P_LOT_NUMBER IN VARCHAR2,
        IO_CURSOR    OUT SYS_REFCURSOR
    )AS BEGIN
        OPEN IO_CURSOR FOR
        SELECT *    
        FROM VIEW_LOT_INFORMATION 
        WHERE LOT_NUMBER = P_LOT_NUMBER; 
    END GET_LOT_INFORMATION;


    /* GET_LOT_LIST_BY_CASE_LABEL */
    PROCEDURE GET_LOT_LIST_BY_CASE_LABEL(
        P_CASE_LABEL_ID IN VARCHAR2,
        P_STORAGE_CODE  IN VARCHAR2,
        IO_CURSOR       OUT SYS_REFCURSOR
    ) IS BEGIN   
    
        --Query  
        OPEN IO_CURSOR FOR
        SELECT LOT.*    
        FROM VIEW_LOT_INFORMATION LOT
        INNER JOIN TABLE(FN_TABLE_STRING(P_STORAGE_CODE)) STORAGE ON FN_INNER_JOIN_IF(LOT.STORAGE_CODE, STORAGE.COLUMN_VALUE) = 'Y'  
        WHERE CASE_LABEL_ID = P_CASE_LABEL_ID                
          AND LOT.IS_DELETED = 'N'
          AND LOT.HAS_DEFECT = 'N';
    END GET_LOT_LIST_BY_CASE_LABEL;


    /* GET_LOT_LIST_BY_LOCATION */
    PROCEDURE GET_LOT_LIST_BY_LOCATION(
        P_LOC_NO  IN VARCHAR2,
        IO_CURSOR OUT SYS_REFCURSOR
    )
    AS BEGIN
        OPEN IO_CURSOR FOR
        SELECT *    
        FROM VIEW_LOT_INFORMATION
        WHERE LOCATION = P_LOC_NO; 
    END GET_LOT_LIST_BY_LOCATION;


    /* GET_STORAGE_LIST */
    PROCEDURE GET_STORAGE_LIST(
        P_FACTORY      IN VARCHAR2, 
        P_STORAGE_TYPE IN VARCHAR2, 
        IO_CURSOR      OUT SYS_REFCURSOR
    ) IS BEGIN 
    
        --Query
        OPEN IO_CURSOR FOR
        SELECT 
            STORAGE.STORAGE_CODE    AS STORAGE_CODE, 
            STORAGE.STORAGE_NAME_EN AS STORAGE_NAME,
            STORAGE.FACTORY         AS FACTORY, 
            STORAGE.STORAGE_TYPE    AS STORAGE_TYPE    
        FROM MES_STORAGE_MA STORAGE
        INNER JOIN TABLE(FN_TABLE_STRING(P_FACTORY))      FACTORY      ON FN_INNER_JOIN_IF(STORAGE.FACTORY, FACTORY.COLUMN_VALUE) = 'Y'   
        INNER JOIN TABLE(FN_TABLE_STRING(P_STORAGE_TYPE)) STORAGE_TYPE ON FN_INNER_JOIN_IF(STORAGE.STORAGE_TYPE, STORAGE_TYPE.COLUMN_VALUE) = 'Y'    
        WHERE STORAGE.USE_FLAG = 'Y'  
        ORDER BY STORAGE.FACTORY, STORAGE.ORDER_SEQ; 
    END GET_STORAGE_LIST;


    /* GET_LOCATION */
    PROCEDURE GET_LOCATION(
        P_LOC_NO    IN  VARCHAR2,  
        P_RACK      IN  VARCHAR2,
        P_RACK_TYPE IN  VARCHAR2,
        IO_CURSOR   OUT SYS_REFCURSOR
    )
    IS BEGIN          

        --Query  
        OPEN IO_CURSOR FOR
        SELECT 
            LOCATION.LOC_NO         AS "LOCATION", 
            LOCATION.RACK_NO        AS "RACK",
            LOCATION.RACK_TYPE1     AS "RACK_TYPE",             
            NVL(LOCATION.ROW_NO, 0) AS "ROW",
            NVL(LOCATION.COL_NO, 0) AS "COLUMN"
        FROM MES_RACK_LOC_MA LOCATION
        INNER JOIN TABLE(FN_TABLE_STRING(P_RACK))      RACK ON FN_INNER_JOIN_IF(LOCATION.RACK_NO, RACK.COLUMN_VALUE) = 'Y'  
        INNER JOIN TABLE(FN_TABLE_STRING(P_RACK_TYPE)) TYPE ON FN_INNER_JOIN_IF(LOCATION.RACK_TYPE1, TYPE.COLUMN_VALUE) = 'Y'  
        WHERE (P_LOC_NO IS NULL OR TRIM(P_LOC_NO) = TRIM(LOC_NO))       
        ORDER BY LOCATION.RACK_TYPE1, LOCATION.RACK_NO, LOCATION.RACK_TYPE1, LOCATION.ROW_NO, LOCATION.COL_NO; 
    END GET_LOCATION;


    /* GET_LOCATION_BY_MATERIAL */
    PROCEDURE GET_LOCATION_BY_MATERIAL (
        P_PART_NO IN  VARCHAR2,
        IO_CURSOR OUT SYS_REFCURSOR
    )IS BEGIN
        
        OPEN IO_CURSOR FOR
        SELECT   
            LOC_MAT.PART_NO         AS "PART_NUMBER",
            LOC_MAT.LOC_NO          AS "LOCATION", 
            LOCATION.RACK_NO        AS "RACK",
            LOCATION.RACK_TYPE1     AS "RACK_TYPE",             
            NVL(LOCATION.ROW_NO, 0) AS "ROW",
            NVL(LOCATION.COL_NO, 0) AS "COLUMN"
        FROM MES_RACK_LOC_PART_MA LOC_MAT
        INNER JOIN MES_RACK_LOC_MA LOCATION ON LOC_MAT.LOC_NO = LOCATION.LOC_NO
        WHERE LOC_MAT.PART_NO = P_PART_NO 
        ORDER BY LOCATION.RACK_TYPE1, LOCATION.RACK_NO, LOCATION.RACK_TYPE1, LOCATION.ROW_NO, LOCATION.COL_NO; 
    END GET_LOCATION_BY_MATERIAL;


    /* GET_PRINTER_LIST */
    PROCEDURE GET_PRINTER_LIST(
        P_PRINTER_NAME IN VARCHAR2,
        IO_CURSOR      OUT SYS_REFCURSOR
    ) 
    AS BEGIN

        OPEN IO_CURSOR FOR
        SELECT 
            PRINTER_NAME,
            IP_ADDRESS            
        FROM MES_PRINTER_MA
        WHERE (P_PRINTER_NAME IS NULL OR P_PRINTER_NAME = PRINTER_NAME);
    END GET_PRINTER_LIST;
END PKG_HWMX_MASTER;