CREATE OR REPLACE PACKAGE BODY PKG_HWMX_MASTER AS  
    
    /* LOGIN */
    PROCEDURE LOGIN(
        P_USER    IN  VARCHAR2,
        P_USER_PW IN  VARCHAR2,
        IO_CURSOR OUT SYS_REFCURSOR
    )IS BEGIN

        OPEN IO_CURSOR FOR
        SELECT USRV.*
        FROM ESAUSER USR
        INNER JOIN VIEW_USER USRV ON USRV."USER" = USR.USR_ID
        WHERE USR.USR_ID  = P_USER
          AND USRV.USE_YN  = 'Y'
          AND USR.SYS_ID  = '100'
          AND CryptIT.DECRYPT(USR.PW) = P_USER_PW;      
    END LOGIN;


    /* GET_USER */
    PROCEDURE GET_USER(
        P_USER    IN VARCHAR2, 
        IO_CURSOR OUT SYS_REFCURSOR
    )IS BEGIN

        OPEN IO_CURSOR FOR
        SELECT USR.*
        FROM VIEW_USER USR
        WHERE P_USER = USR."USER";      
    END GET_USER;


    /* GET_USER_LIST */
    PROCEDURE GET_USER_LIST( 
        P_DEPT_CD     IN VARCHAR2,
        P_ONLY_ACTIVE IN VARCHAR2,
        IO_CURSOR     OUT SYS_REFCURSOR
    )IS BEGIN

        OPEN IO_CURSOR FOR
        SELECT *
        FROM VIEW_USER USR
        WHERE (P_DEPT_CD IS NULL   OR P_DEPT_CD = USR.DEPARTMENT_CODE)
          AND (P_ONLY_ACTIVE = 'N' OR USR.USE_YN = 'Y');      
    END GET_USER_LIST;


    /* GET_LOT_INFORMATION */
    PROCEDURE GET_LOT_INFORMATION(
        P_LOT_NUMBER IN VARCHAR2,
        IO_CURSOR    OUT SYS_REFCURSOR
    )
    AS BEGIN
        OPEN IO_CURSOR FOR
        SELECT *    
        FROM VIEW_LOT_INFORMATION 
        WHERE LOT_NUMBER = P_LOT_NUMBER; 
    END GET_LOT_INFORMATION;


    /* GET_LOT_LIST_BY_CASE_LABEL */
    PROCEDURE GET_LOT_LIST_BY_CASE_LABEL(
        P_CASE_LABEL_ID IN VARCHAR2,
        P_STORAGE_CODE  IN VARCHAR2,
        IO_CURSOR       OUT SYS_REFCURSOR
    ) IS 
    BEGIN 
        OPEN IO_CURSOR FOR
        SELECT *    
        FROM VIEW_LOT_INFORMATION
        WHERE CASE_LABEL_ID = P_CASE_LABEL_ID                
          AND IS_DELETED = 'N'
          AND HAS_DEFECT = 'N'
          AND (P_STORAGE_CODE IS NULL OR P_STORAGE_CODE = STORAGE_CODE);
    END GET_LOT_LIST_BY_CASE_LABEL;


    /* GET_LOT_LIST_BY_LOCATION */
    PROCEDURE GET_LOT_LIST_BY_LOCATION(
        P_LOC_NO  IN VARCHAR2,
        IO_CURSOR OUT SYS_REFCURSOR
    )
    AS BEGIN
        OPEN IO_CURSOR FOR
        SELECT *    
        FROM VIEW_LOT_INFORMATION
        WHERE LOCATION = P_LOC_NO; 
    END GET_LOT_LIST_BY_LOCATION;


    /* GET_STORAGE_LIST */
    PROCEDURE GET_STORAGE_LIST(
        P_FACTORY      IN VARCHAR2, 
        P_STORAGE_TYPE IN VARCHAR2, 
        IO_CURSOR      OUT SYS_REFCURSOR
    )
    AS BEGIN
        OPEN IO_CURSOR FOR
        SELECT 
            STORAGE_CODE    AS STORAGE_CODE, 
            STORAGE_NAME_EN AS STORAGE_NAME,
            FACTORY         AS FACTORY, 
            STORAGE_TYPE    AS STORAGE_TYPE    
        FROM MES_STORAGE_MA
        WHERE USE_FLAG = 'Y' 
          AND (P_FACTORY IS NULL      OR P_FACTORY = FACTORY)
          AND (P_STORAGE_TYPE IS NULL OR P_STORAGE_TYPE = STORAGE_TYPE)
        ORDER BY FACTORY, ORDER_SEQ; 
    END GET_STORAGE_LIST;


    /* GET_LOCATION */
    PROCEDURE GET_LOCATION(
        P_LOC_NO    IN VARCHAR2,  
        P_RACK      IN VARCHAR2,
        P_RACK_TYPE IN VARCHAR2,
        IO_CURSOR   OUT SYS_REFCURSOR
    )
    IS 
        V_RACK      ARRAY_STRING;
        V_RACK_TYPE ARRAY_STRING;
    BEGIN
        --V_RACK
        IF FC_IS_NOT_EMPTY(P_RACK) = 'Y' THEN
            WITH CTE_RACK AS (
                SELECT * FROM TABLE(FC_SPLIT(P_RACK, ';'))
            )    
            SELECT COLUMN_VALUE 
            BULK COLLECT INTO V_RACK
            FROM CTE_RACK;
            
        ELSE    
            SELECT NULL 
            BULK COLLECT INTO V_RACK
            FROM DUAL;
        END IF; 
        
        --V_RACK_TYPE
        IF FC_IS_NOT_EMPTY(P_RACK_TYPE) = 'Y' THEN
            WITH CTE_RACK_TYPE AS (
                SELECT * FROM TABLE(FC_SPLIT(P_RACK_TYPE, ';'))
            )    
            SELECT COLUMN_VALUE 
            BULK COLLECT INTO V_RACK_TYPE
            FROM CTE_RACK_TYPE;
        ELSE    
            SELECT NULL 
            BULK COLLECT INTO V_RACK_TYPE
            FROM DUAL;
        END IF; 

        --Query  
        OPEN IO_CURSOR FOR
        SELECT 
            LOCATION.LOC_NO         AS "LOCATION", 
            LOCATION.RACK_NO        AS "RACK",
            LOCATION.RACK_TYPE1     AS "RACK_TYPE",             
            NVL(LOCATION.ROW_NO, 0) AS "ROW",
            NVL(LOCATION.COL_NO, 0) AS "COLUMN"
        FROM MES_RACK_LOC_MA LOCATION
        INNER JOIN TABLE(V_RACK)      RACK ON LOCATION.RACK_NO    = (CASE WHEN V_RACK(1)      IS NULL THEN LOCATION.RACK_NO    ELSE RACK.COLUMN_VALUE END)
        INNER JOIN TABLE(V_RACK_TYPE) TYPE ON LOCATION.RACK_TYPE1 = (CASE WHEN V_RACK_TYPE(1) IS NULL THEN LOCATION.RACK_TYPE1 ELSE TYPE.COLUMN_VALUE END)
        WHERE (P_LOC_NO IS NULL OR TRIM(P_LOC_NO) = TRIM(LOC_NO))       
        ORDER BY LOCATION.RACK_TYPE1, LOCATION.RACK_NO, LOCATION.RACK_TYPE1, LOCATION.ROW_NO, LOCATION.COL_NO; 
    END GET_LOCATION;


    /* GET_PRINTER_LIST */
    PROCEDURE GET_PRINTER_LIST(
        P_PRINTER_NAME IN VARCHAR2,
        P_CURSOR       OUT SYS_REFCURSOR
    ) 
    AS BEGIN

        OPEN P_CURSOR FOR
        SELECT 
            PRINTER_NAME,
            IP_ADDRESS            
        FROM MES_PRINTER_MA
        WHERE (P_PRINTER_NAME IS NULL OR P_PRINTER_NAME = PRINTER_NAME);
    END GET_PRINTER_LIST;
END PKG_HWMX_MASTER;